services:
  tf-gpu:
    build: .
    container_name: tf-gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/workspace
      - ~/development/data:/data
    working_dir: /workspace
    tty: true
